# Generated by Django 4.2.1 on 2023-05-29 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
