# Generated by Django 4.2.1 on 2023-07-23 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_auto_20230723_1355'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='date',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='word',
            name='score',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
